# Generated by Django 3.0.1 on 2020-01-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200104_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Cocktail',
        ),
    ]
