# Generated by Django 3.0.1 on 2020-02-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200104_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='creator',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
    ]
