# Generated by Django 3.0.1 on 2020-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_cocktail_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='glass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, verbose_name='date Created'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
